version: "3.8"

networks:
  rabbit:
    external: true

x-defaults: &defaults
  restart: always
  networks:
    - rabbit

x-logging: &logging
  logging:
    driver: "fluentd"
    options:
      fluentd-address: localhost:24224
  

services:
  keepalived:
    <<: *logging
    hostname: keepalived
    container_name: keepalived
    image: osixia/keepalived:2.0.20
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    environment:
      KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
        --log-detail
        #-–dont-release-vrrp
        #-–dont-release-ipvs
        #--dump-conf
    network_mode: host
    volumes:
      - ./keepalived/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro
  
  haproxy:
    <<: *logging
    <<: *defaults
    image: haproxy:2.3.7
    hostname: haproxy
    container_name: haproxy
    extra_hosts:
      - ${RABBITMQ_REMOTE_HOST_NAME}:${RABBITMQ_REMOTE_HOST_IP}
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      LOCAL: ${RABBITMQ_CONTAINER_NAME}
      REMOTE: ${RABBITMQ_REMOTE_HOST_NAME}
    ports:
      - 8080:8080
      - 5673:5673

  haproxy_exporter:
    <<: *logging
    <<: *defaults
    image: quay.io/prometheus/haproxy-exporter:v0.12.0
    hostname: haproxy-exporter
    container_name: haproxy-exporter
    command: 
      - --haproxy.scrape-uri=http://nanoit:admin@haproxy:8080/stats?stats;csv
    ports:
      - 9101:9101

  node-exporter:
    <<: *logging
    <<: *defaults
    image: prom/node-exporter:latest
    hostname: node-exporter
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100

  cadvisor:
    <<: *logging
    <<: *defaults
    image: google/cadvisor:latest
    hostname: cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    ports:
      - 8070:8080

  rabbit:
    <<: *logging
    <<: *defaults
    image: rabbitmq:3.8.14-management-alpine
    hostname: ${RABBITMQ_CONTAINER_NAME}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    extra_hosts:
      - ${RABBITMQ_REMOTE_HOST_NAME}:${RABBITMQ_REMOTE_HOST_IP}
    environment:
      LOCAL_DOMAIN: ${RABBITMQ_CONTAINER_NAME}
      REMOTE_DOMAIN: ${RABBITMQ_REMOTE_HOST_NAME}
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 15692:15692
      - 25672:25672

